DELETE FROM Traducciones;
GO
DELETE FROM Tags;
GO
DELETE FROM Idiomas;
GO
INSERT INTO Idiomas(Nombre) VALUES('Español');
INSERT INTO Idiomas(Nombre) VALUES('Ingles');
GO
INSERT INTO Tags (nombre) VALUES
('label_ingresar_email'),
('label_ingresar_contraseña'),
('label_iniciar_sesion'),
('label_sesion'),
('label_cerrar_sesion'),
('label_permisos'),
('label_productos'),
('label_usuarios'),
('label_idiomas'),
('label_traducciones'),
('label_agregar_usuario'),
('label_editar_usuario'),
('label_asignar_permiso'),
('label_borrar_usuario'),
('label_cancelar'),
('label_aceptar'),
('label_agregar_producto'),
('label_editar_producto'),
('label_borrar_producto'),
('label_agregar_idioma'),
('label_editar_idioma'),
('label_borrar_idioma'),
('label_agregar_traduccion'),
('label_editar_traduccion'),
('label_borrar_traduccion'),
('label_traducciones_idioma'),
('label_seleccionar_idioma'),
('label_agregar_permiso'),
('label_editar_permiso'),
('label_vincular_permisos'),
('label_borrar_permiso'),
('label_vincular'),
('label_nombre'),
('label_es_padre'),
('label_precio'),
('label_apellido'),
('label_dni'),
('label_email'),
('label_contraseña'),
('label_bitacora'),
('label_historico'),
('label_reestablecer');
GO
INSERT INTO Traducciones (idIdioma, idTag, traduccion) VALUES
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_ingresar_email'), 'Ingresar Email'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_ingresar_contraseña'), 'Ingresar Contraseña'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_iniciar_sesion'), 'Iniciar Sesion'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_sesion'), 'Sesion'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_cerrar_sesion'), 'Cerrar Sesion'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_permisos'), 'Permisos'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_productos'), 'Productos'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_usuarios'), 'Usuarios'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_idiomas'), 'Idiomas'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_traducciones'), 'Traducciones'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_agregar_usuario'), 'Agregar Usuario'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_editar_usuario'), 'Editar Usuario'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_asignar_permiso'), 'Asignar Permiso'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_borrar_usuario'), 'Borrar Usuario'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_cancelar'), 'Cancelar'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_aceptar'), 'Aceptar'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_agregar_producto'), 'Agregar Producto'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_editar_producto'), 'Editar Producto'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_borrar_producto'), 'Borrar Producto'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_agregar_idioma'), 'Agregar Idioma'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_editar_idioma'), 'Editar Idioma'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_borrar_idioma'), 'Borrar Idioma'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_agregar_traduccion'), 'Agregar Traduccion'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_editar_traduccion'), 'Editar Traduccion'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_borrar_traduccion'), 'Borrar Traduccion'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_traducciones_idioma'), 'Traducciones del idioma seleccionado'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_seleccionar_idioma'), 'Seleccionar idioma'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_agregar_permiso'), 'Agregar Permiso'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_editar_permiso'), 'Editar Permiso'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_vincular_permisos'), 'Vincular Permisos'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_borrar_permiso'), 'Borrar Permiso'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_vincular'), 'Vincular'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_nombre'), 'Nombre'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_es_padre'), 'Es Padre'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_precio'), 'Precio'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_apellido'), 'Apellido'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_dni'), 'Dni'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_email'), 'Email'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_contraseña'), 'Contraseña'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_bitacora'), 'Bitacora'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_historico'), 'Historico'),
((SELECT id FROM Idiomas WHERE nombre = 'Español'), (SELECT id FROM Tags WHERE nombre = 'label_reestablecer'), 'Reestablecer valor');
GO
INSERT INTO Traducciones (idIdioma, idTag, traduccion) VALUES
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_ingresar_email'), 'Enter Email'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_ingresar_contraseña'), 'Enter Password'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_iniciar_sesion'), 'Sign In'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_sesion'), 'Session'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_cerrar_sesion'), 'Sign Out'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_permisos'), 'Permissions'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_productos'), 'Products'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_usuarios'), 'Users'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_traducciones'), 'Traductions'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_idiomas'), 'Languages'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_agregar_usuario'), 'Add User'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_editar_usuario'), 'Edit User'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_asignar_permiso'), 'Assign Permission'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_borrar_usuario'), 'Delete User'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_cancelar'), 'Cancel'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_aceptar'), 'Accept'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_agregar_producto'), 'Add Product'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_editar_producto'), 'Edit Product'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_borrar_producto'), 'Delete Product'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_agregar_idioma'), 'Add Language'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_editar_idioma'), 'Edit Language'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_borrar_idioma'), 'Delete Language'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_agregar_traduccion'), 'Add Traduction'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_editar_traduccion'), 'Edit Traduction'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_borrar_traduccion'), 'Delete Traduction'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_traducciones_idioma'), 'Translations of the selected language'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_seleccionar_idioma'), 'Select languaje'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_agregar_permiso'), 'Add Permission'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_editar_permiso'), 'Edit Permission'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_vincular_permisos'), 'Link Permissions'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_borrar_permiso'), 'Delete Permission'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_vincular'), 'Link'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_nombre'), 'First Name'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_es_padre'), 'Is Parent'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_precio'), 'Price'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_apellido'), 'Last Name'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_dni'), 'National ID'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_email'), 'Email'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_contraseña'), 'Password'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_bitacora'), 'Binnacle'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_historico'), 'Historic'),
((SELECT id FROM Idiomas WHERE nombre = 'Ingles'), (SELECT id FROM Tags WHERE nombre = 'label_reestablecer'), 'Reset value');
